# Generated by Django 5.0.6 on 2024-07-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inmueble_num_habitaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='precio_ufs',
        ),
    ]
