# Generated by Django 5.0.6 on 2024-07-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_userprofilusuario_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
