# Generated by Django 5.0.6 on 2024-07-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inmueble_eliminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='eliminado',
        ),
    ]
